### ISSUE TITLE
Sprint TODO

### ISSUE THREAD

**Issue by ryanccarelli** [Dana-Farber-AIOS/pathml#69]
TODO weekend sprint:
repo structure:
pathml
>utils.py
-> core
-> preprocessing
-> ml
-> datasets

refactor:
- [ ] SlideData
  - [x] tests
  - [ ] in run add multiprocessing pool for tiles
  - [ ] save method
- [x] Slide and Subclasses
  - [x] tests
- [ ] Masks and Tiles
  - [x] tests
  - [x] polish docstrings
  - [ ] documentation
- [x] Refactor transforms
  - [x] tests
  - [x] docs
- [x] Rewrite documentation
  - [x] update examples
- [x] Integration tests
